[[repos]]
url = "https://raw.githubusercontent.com/leftwm/leftwm-community-themes/master/known.toml"
name = "community"
definitions_version = 0

[[repos.themes]]
name = "Orange Forest"
directory = "/home/eric/.config/leftwm/themes/Orange Forest"
repository = "https://github.com/PVautour/leftwm-theme-orange-forest/"
commit = "*"
version = "0.0.2"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "Coffee"
directory = "/home/eric/.config/leftwm/themes/Coffee"
repository = "https://github.com/lex148/leftwm-coffee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Soothe"
directory = "/home/eric/.config/leftwm/themes/Soothe"
repository = "https://github.com/b4skyx/leftwm-soothe/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false
relative_directory = "theme/"

[[repos.themes]]
name = "TNG"
directory = "/home/eric/.config/leftwm/themes/TNG"
repository = "https://github.com/lex148/leftwm-tng/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Windows XP"
repository = "https://github.com/lex148/leftwm-windowsxp/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Dracula Rounded"
directory = "/home/eric/.config/leftwm/themes/Dracula Rounded"
repository = "https://github.com/AethanFoot/leftwm-theme-dracula-rounded/"
commit = "*"
version = "0.0.3"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "Forest"
directory = "/home/eric/.config/leftwm/themes/Forest"
repository = "https://github.com/lex148/forest/"
commit = "*"
version = "0.0.1"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "Ground Zero"
directory = "/home/eric/.config/leftwm/themes/Ground Zero"
repository = "https://github.com/Qwart376/Ground-Zero/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Red Moon"
directory = "/home/eric/.config/leftwm/themes/Red Moon"
repository = "https://github.com/Qwart376/Red-Moon"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Blue Coffee"
repository = "https://github.com/Qwart376/Blue-Coffee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "sunflower"
repository = "https://github.com/mautamu/leftwm-sunflower/"
commit = "*"
version = "0.1.2"
leftwm_versions = "^0.2.11, <0.3.0"
current = false

[[repos.themes]]
name = "Bumblebee"
directory = "/home/eric/.config/leftwm/themes/Bumblebee"
repository = "https://github.com/mfdorst/leftwm-bumblebee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "^0.2.8, <0.3.0"
current = false

[[repos.themes]]
name = "Changed Sunset"
repository = "https://github.com/Syudagye/changed-sunset"
commit = "*"
version = "0.0.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Garden"
repository = "https://github.com/taylor85345/leftwm-theme-garden"
commit = "*"
version = "0.0.4"
leftwm_versions = ">0.2.7"
current = false

[[repos.themes]]
name = "Epitaph"
repository = "https://github.com/VentGrey/Epitaph"
commit = "*"
version = "0.0.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Ocean-night"
repository = "https://github.com/TheRoniOne/ocean-night"
commit = "*"
version = "0.0.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Flamingo"
repository = "https://github.com/necaris/leftwm-theme-flamingo"
commit = "*"
version = "0.0.1"
leftwm_versions = ">0.2.7, <0.3.0"
current = false

[[repos.themes]]
name = "Sunset"
repository = "https://github.com/Syudagye/leftwm-sunset"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Amber"
directory = "/home/eric/.config/leftwm/themes/Amber"
repository = "https://github.com/di-effe/amber"
commit = "*"
version = "0.2.2"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Catppuccin"
directory = "/home/eric/.config/leftwm/themes/Catppuccin"
repository = "https://github.com/di-effe/catppuccin"
commit = "*"
version = "0.1.1"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Molese"
repository = "https://github.com/m0lese/leftwm-config"
commit = "*"
version = "2.1.0"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Double Bar"
repository = "https://github.com/PeterDauwe/doublebar/"
commit = "*"
version = "0.0.2"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "SpaceJelly"
directory = "/home/eric/.config/leftwm/themes/SpaceJelly"
repository = "https://gitlab.com/jchand99/space_jelly"
commit = "*"
version = "1.0.0"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Ascent"
directory = "/home/eric/.config/leftwm/themes/Ascent"
repository = "https://gitlab.com/mWalrus/ascent"
commit = "*"
version = "1.0.0"
leftwm_versions = ">0.2.7"
current = false

[[repos.themes]]
name = "Zexanima"
repository = "https://github.com/calebgasser/zexanima-leftwm-theme/tree/develop"
commit = "*"
version = "0.0.1"
leftwm_versions = ">0.3.0"
current = false

[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 0

[[repos.themes]]
name = "candy"
directory = "/home/eric/.config/leftwm/themes/candy"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "controlling_leftwm"
directory = "/home/eric/.config/leftwm/themes/controlling_leftwm"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "basic_xmobar"
directory = "/home/eric/.config/leftwm/themes/basic_xmobar"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "basic_polybar"
directory = "/home/eric/.config/leftwm/themes/basic_polybar"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "basic_lemonbar"
directory = "/home/eric/.config/leftwm/themes/basic_lemonbar"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "forest (Case Conflict)"
directory = "/home/eric/.config/leftwm/themes/forest (Case Conflict)"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos]]
url = "https://raw.githubusercontent.com/arcolinux/arcolinux-leftwm-themes/master/known.toml"
name = "arcolinux"
definitions_version = 0

[[repos.themes]]
name = "docky"
directory = "/home/eric/.config/leftwm/themes/docky"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-docky/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "eden"
directory = "/home/eric/.config/leftwm/themes/eden"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-eden/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "material"
directory = "/home/eric/.config/leftwm/themes/material"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-material/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "mesh"
directory = "/home/eric/.config/leftwm/themes/mesh"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-mesh/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "matrix"
directory = "/home/eric/.config/leftwm/themes/matrix"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-matrix/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "parker"
directory = "/home/eric/.config/leftwm/themes/parker"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-parker/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "pi"
directory = "/home/eric/.config/leftwm/themes/pi"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-pi/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "shades"
directory = "/home/eric/.config/leftwm/themes/shades"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-shades/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "space"
directory = "/home/eric/.config/leftwm/themes/space"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-space/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "starwars"
directory = "/home/eric/.config/leftwm/themes/starwars"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-starwars/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "smooth"
directory = "/home/eric/.config/leftwm/themes/smooth"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-smooth/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "forest"
directory = "/home/eric/.config/leftwm/themes/forest"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-forest/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "grayblocks"
directory = "/home/eric/.config/leftwm/themes/grayblocks"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-grayblocks/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "greyblocks"
directory = "/home/eric/.config/leftwm/themes/greyblocks"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-greyblocks/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "halo"
directory = "/home/eric/.config/leftwm/themes/halo"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-halo/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db"
directory = "/home/eric/.config/leftwm/themes/db"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-scifi-star"
directory = "/home/eric/.config/leftwm/themes/db-scifi-star"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db-scifi-star/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "arise"
directory = "/home/eric/.config/leftwm/themes/arise"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-arise/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = true

[[repos.themes]]
name = "db-nemesis"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db-nemesis/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false

[[repos]]
url = "https://raw.githubusercontent.com/arcolinux/arcolinux-leftwm-themes-community/main/known.toml"
name = "arcolinux-community"
definitions_version = 0

[[repos.themes]]
name = "doublebar"
directory = "/home/eric/.config/leftwm/themes/doublebar"
repository = "https://github.com/PeterDauwe/doublebar/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-color-dev"
directory = "/home/eric/.config/leftwm/themes/db-color-dev"
repository = "https://github.com/PeterDauwe/db-color-dev"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-scifi"
directory = "/home/eric/.config/leftwm/themes/db-scifi"
repository = "https://github.com/PeterDauwe/db-scifi"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-labels"
directory = "/home/eric/.config/leftwm/themes/db-labels"
repository = "https://github.com/PeterDauwe/db-labels"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-comic"
directory = "/home/eric/.config/leftwm/themes/db-comic"
repository = "https://github.com/PeterDauwe/db-comic"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "sb-horror"
directory = "/home/eric/.config/leftwm/themes/sb-horror"
repository = "https://github.com/PeterDauwe/sb-horror"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "kittycafe-sm"
repository = "https://github.com/etrigan63/kittycafe-sm"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "kittycafe-dm"
directory = "/home/eric/.config/leftwm/themes/kittycafe-dm"
repository = "https://github.com/etrigan63/kittycafe-dm"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false
